{
    'name': 'Casper Ventures',
    'version': '17.0.0.1.44',
    'summary': 'Casper Ventures specific implementations',
    'category': 'Accounting/Localizations/Reporting',
    'depends': [
        'account','l10n_pt_reports_arxi', 'account_batch_payment', 'sale', 'account_followup', 'fleet',
        'hr_timesheet', 'project', 'hr_expense', 'website_sale', 'account_accountant', 'l10n_pt_sale', 'base', 'website',
        'sale_subscription',
    ],
    'data': [
        'security/ir.model.access.csv',

        'data/ir_cron.xml',
        'data/balance_sheet.xml',
        'data/mail_data.xml',
        'data/hr_data.xml',
        'data/fleet_data.xml',
        'data/fleet_service_type.xml',
        'data/res_lang_data.xml',
        'data/daily_company_position_mail_template.xml',
        'data/mail_approval_template.xml',

        'reports/report_payment_receipt.xml',
        'reports/shared_tax_totals_brainr.xml',
        'reports/account_custom_report_brainr.xml',
        'reports/sale_custom_report_brainr.xml',
        'reports/sale_subscription_custom_report.xml',

        'views/fleet_vehicle_views.xml',
        'views/account_batch_payment_views.xml',
        'views/res_partner_views.xml',
        'views/sale_views.xml',
        'views/hr_expense_views.xml',
        'views/account_journal_dashboard_views.xml',
        'views/account_followup_views.xml',
        'views/res_config_setting_views.xml',
        'views/analytic_account_views.xml',
        'views/project_views.xml',
        'views/report_statement.xml',
        'views/res_company_views.xml',
        'views/sale_order_journal_view_form.xml',
        'views/hr_employee_views.xml',
        'views/account_move_views.xml',
    ],
    'license': 'OPL-1',
}
