from . import res_config_settings
from . import hr_contract
from . import analytic_account
from . import account_analytic_line
from . import fleet_vehicle
from . import account_move
from . import project
from . import res_company
from . import account_journal
from . import bank_rec_widget
from . import sale_order_journal
from . import sale_order
from . import payment_transaction
from . import product_template
from . import hr_expense
from . import account_edi_common
from . import account_invoice_report
from . import account_payment_batch